# Core Colors
background            #10140f
foreground            #e0e4da
selection_foreground  #263422
selection_background  #a3d398
cursor                #a3d398
cursor_text_color     #263422

# Regular Colors
color0  #10140f
color1  #ffb4ab
color2  #a3d398
color3  #a0cfd3
color4  #265022
color5  #3c4b38
color6  #baccb3
color7  #e0e4da

# Bright Colors (lighter/more vivid variants)
color8  #42493f
color9  #93000a
color10 #bef0b2
color11 #bcebef
color12 #bef0b2
color13 #d6e8ce
color14 #d6e8ce
color15 #363a34
