# Core Colors
background            #101418
foreground            #e1e2e8
selection_foreground  #253140
selection_background  #9fcafc
cursor                #9fcafc
cursor_text_color     #253140

# Regular Colors
color0                #1e222a
color1                #e05f65
color2                #78dba9
color3                #f1cf8a
color4                #a8c8ff
color5                #dbbce1
color6                #74bee9

# Brighter Colors
color7                #c5c6cc
color8                #43474e
color9                #fc7b81
color10               #94f7c5
color11               #ffeba6
color12               #d5e3ff
color13               #f8d8fe
color14               #90daff
color15               #e1e2e9
