[config.wallpaper]
command = "awww"
arguments = ["img", "--transition-type", "any", "--transition-fps", "60"]
set = false

# [templates.waybar]
# input_path = '~/.config/matugen/templates/colors.css'
# output_path = '~/.config/waybar/colors.css'
# post_hook = 'pkill -SIGUSR2 waybar'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

# [templates.wofi]
# input_path = '~/.config/matugen/templates/colors.css'
# output_path = '~/.config/wofi/colors.css'

# [templates.YouTubeMusic]
# input_path = '~/.config/matugen/templates/colors.css'
# output_path = '~/.config/YouTube Music/colors.css'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = "pkill -SIGUSR1 kitty"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

#[templates.gtk3]
#input_path = '~/.config/matugen/templates/gtk-colors.css'
#output_path = '~/.config/gtk-3.0/colors.css'

#[templates.gtk4]
#input_path = '~/.config/matugen/templates/gtk-colors.css'
#output_path = '~/.config/gtk-4.0/colors.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

#[templates.cava]
#input_path = '~/.config/matugen/templates/matugen-cava'
#output_path = '~/.config/cava/config'
#post_hook = "pkill -USR1 cava"

#[templates.spicetify]
#input_path = '~/.config/matugen/templates/spotify-colors.ini'
#output_path = '~/.config/spicetify/Themes/text/color.ini'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/matugen.css'

[templates.ohmyposh]
input_path  = '~/.config/matugen/templates/ohmyposh-safe.json'
output_path = '~/.config/ohmyposh/colors.json'
post_hook = '~/.config/hypr/scripts/ohmyposh.sh; pkill -USR1 fish'

# [templates.todo]
# input_path = '~/.config/matugen/templates/todo.css'
# output_path = '~/.config/ToDo/style.qss'
# post_hook = 'pkill todo-app'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux.conf'
output_path = '~/.config/tmux/tmux.conf'
post_hook = 'tmux source-file ~/.config/tmux/tmux.conf'

[templates.quickshell]
input_path = '~/.config/matugen/templates/Theme.qml'
output_path = '~/.config/quickshell/Theme.qml'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync.css'
output_path = '~/.config/swaync/style.css'
post_hook = 'pkill swaync; swaync &'

[templates.nvim_pallette]
input_path = "~/.config/matugen/templates/palette.lua"
output_path = "~/.config/nvim/lua/matugen-nvim/lua/matugen/palette.lua"
post_hook = "~/scripts/nvim-reload.sh"

[templates.gtk]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.local/share/themes/frosted/gtk-3.0/colors.css'
post_hook = 'pkill nemo'
