unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.tmux.conf \; display "Reloaded!"

set -g base-index 1
setw -g pane-base-index 1

set -g mouse on

setw -g mode-keys vi

# position (top or bottom)
set -g status-position bottom

# bar colors
set -g status-style bg=#0f1416,fg=#dee3e6

# left and right sections
set -g status-left "#[fg=#88d1ec] #S "
set -g status-right "#[fg=#c3c3eb] %H:%M #[fg=#88d1ec] %d-%m-%Y "

# current window style
setw -g window-status-current-style fg=#0f1416,bg=#88d1ec,bold
setw -g window-status-current-format " #I #W "

# inactive window style
setw -g window-status-style fg=#dee3e6
setw -g window-status-format " #I #W "

# bar length
set -g status-left-length 20
set -g status-right-length 40

