# ---- palette (templater fills these in) ----
set -g @c_surface "#111318"
set -g @c_inverse_surface "#e1e2e9"
set -g @c_primary "#a7c8ff"
set -g @c_tertiary "#dbbde2"

# ---- keybinds / behavior ----
unbind C-b
set -g prefix C-a
bind C-a send-prefix

unbind r
bind-key -T prefix r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded!"

set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
setw -g mode-keys vi
set -g status-position bottom

# ---- status bar ----
set -g status-style "bg=#{@c_surface},fg=#{@c_inverse_surface}"

set -g status-left "#[fg=#{@c_primary}] #S "
set -g status-right "#[fg=#{@c_tertiary}] %H:%M #[fg=#{@c_primary}] %d-%m-%Y "

# ---- windows ----
setw -g window-status-current-style "fg=#{@c_surface},bg=#{@c_primary},bold"
setw -g window-status-current-format " #I #W "

setw -g window-status-style "fg=#{@c_inverse_surface}"
setw -g window-status-format " #I #W "

set -g status-left-length 20
set -g status-right-length 40
