preload=/home/brian/Wallpapers/powerline_green.jpg
preload=/home/brian/Wallpapers/vaporwave1.png
preload=/home/brian/Wallpapers/pinksun.jpg
preload=/home/brian/Wallpapers/chair_on_platform.jpg
preload=/home/brian/Wallpapers/man_in_chair.png
preload=/home/brian/Wallpapers/mountains_and_trees.png
preload=/home/brian/Wallpapers/skeleton.png
preload=/home/brian/Wallpapers/swirls_of_paint.jpg
preload=/home/brian/Wallpapers/japan_river.jpg
preload=/home/brian/Wallpapers/weeb.png
preload=/home/brian/Wallpapers/vaporwave_river.jpg
wallpaper=eDP-1,/home/brian/Wallpapers/powerline_green.jpg
wallpaper=HDMI-A-2,/home/brian/Wallpapers/powerline_green.jpg
