general {
    lock_cmd = hyprlock          # dbus/loginctl lock command
    before_sleep_cmd = loginctl lock-session
    ignore_dbus_inhibit = false  # ignores lock requests from browsers/video players
}

listener {
    timeout = 300                # 5 minutes
    on-timeout = hyprlock        # command to run when timeout has passed
}

listener {
    timeout = 600                # 10 minutes
    on-timeout = systemctl suspend
}
