exec-once = awww-daemon
exec-once = sudo ydotoold --socket-perm 0666
exec-once = ~/.config/hypr/scripts/battery-notif.sh
exec-once = qs -p ~/.config/quickshell/shell.qml
exec-once = libinput-gestures-setup start
exec-once = sleep 0.5 && hyprlock
