bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, F, exec, zen-browser
bind = $mainMod, D, exec, vesktop
bind = $mainMod, T, killactive,
bind = $mainMod, A, exec, ~/.config/hypr/scripts/application_launcher.sh
bind = $mainMod, N, exec, qs ipc call network toggle
bind = $mainMod, E, exec, $fileManager
bind = $mainMod SHIFT, E, exec, rofimoji
bind = $mainMod, V, togglefloating,
bind = $mainMod, I, exec, ~/.config/hypr/scripts/toggle-todo.sh
bind = $mainMod, P, exec, ~/.config/hypr/scripts/wlogout.sh
bind = $mainMod, R, layoutmsg, togglesplit
bind = $mainMod, S, exec, steam
# bind = $mainMod, W, exec, ~/.config/hypr/scripts/wallpaper.sh
bind = $mainMod, W, exec, qs ipc call wallpaper toggle
bind = $mainMod, B, exec, qs ipc call bluetooth toggle
bind = $mainMod, Print, exec, ~/.config/hypr/scripts/screenshot.sh
bind = $mainMod SHIFT, F, fullscreen, 1
bind = $mainMod, 8, exec, qs ipc call 8ball toggle

bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

binde = ALT SHIFT, h, resizeactive, -40 0
binde = ALT SHIFT, l, resizeactive, 40 0
binde = ALT SHIFT, k, resizeactive, 0 -40
binde = ALT SHIFT, j, resizeactive, 0 40

binde = $mainMod CTRL, h, moveactive, -40 0
binde = $mainMod CTRL, l, moveactive, 40 0
binde = $mainMod CTRL, k, moveactive, 0 -40
binde = $mainMod CTRL, j, moveactive, 0 40

# Two Monitors
bind = $mainMod, 1, exec, hyprctl dispatch workspace $(( $(hyprctl monitors -j | jq '.[] | select(.focused == true).id') * 5 + 1 ))
bind = $mainMod, 2, exec, hyprctl dispatch workspace $(( $(hyprctl monitors -j | jq '.[] | select(.focused == true).id') * 5 + 2 ))
bind = $mainMod, 3, exec, hyprctl dispatch workspace $(( $(hyprctl monitors -j | jq '.[] | select(.focused == true).id') * 5 + 3 ))
bind = $mainMod, 4, exec, hyprctl dispatch workspace $(( $(hyprctl monitors -j | jq '.[] | select(.focused == true).id') * 5 + 4 ))
bind = $mainMod, 5, exec, hyprctl dispatch workspace $(( $(hyprctl monitors -j | jq '.[] | select(.focused == true).id') * 5 + 5 ))

bind = $mainMod SHIFT, 1, exec, hyprctl dispatch movetoworkspace $(( $(hyprctl monitors -j | jq '.[] | select(.focused == true).id') * 5 + 1 ))
bind = $mainMod SHIFT, 2, exec, hyprctl dispatch movetoworkspace $(( $(hyprctl monitors -j | jq '.[] | select(.focused == true).id') * 5 + 2 ))
bind = $mainMod SHIFT, 3, exec, hyprctl dispatch movetoworkspace $(( $(hyprctl monitors -j | jq '.[] | select(.focused == true).id') * 5 + 3 ))
bind = $mainMod SHIFT, 4, exec, hyprctl dispatch movetoworkspace $(( $(hyprctl monitors -j | jq '.[] | select(.focused == true).id') * 5 + 4 ))
bind = $mainMod SHIFT, 5, exec, hyprctl dispatch movetoworkspace $(( $(hyprctl monitors -j | jq '.[] | select(.focused == true).id') * 5 + 5 ))

# One Monitor
# bind = $mainMod, 1, exec, hyprctl dispatch workspace 1
# bind = $mainMod, 2, exec, hyprctl dispatch workspace 2
# bind = $mainMod, 3, exec, hyprctl dispatch workspace 3
# bind = $mainMod, 4, exec, hyprctl dispatch workspace 4
# bind = $mainMod, 5, exec, hyprctl dispatch workspace 5
# 
# bind = $mainMod SHIFT, 1, exec, hyprctl dispatch movetoworkspace 1
# bind = $mainMod SHIFT, 2, exec, hyprctl dispatch movetoworkspace 2
# bind = $mainMod SHIFT, 3, exec, hyprctl dispatch movetoworkspace 3
# bind = $mainMod SHIFT, 4, exec, hyprctl dispatch movetoworkspace 4
# bind = $mainMod SHIFT, 5, exec, hyprctl dispatch movetoworkspace 5

bind = $mainMod, mouse_down, workspace, e-1
bind = $mainMod, mouse_up, workspace, e+1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = , mouse_right, workspace, e+1
bind = , mouse_left, workspace, e-1
