input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = true
        drag_3fg = 0
    }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

cursor {
    no_hardware_cursors = true
}

misc {
    # vfr = true          # variable frame rate - reduces GPU load on idle monitors
}
