windowrule = fullscreen on, match:class ^(steam_app_.*)$

windowrule = float on, match:class ^(todo-app)$
windowrule = center on, match:class ^(todo-app)$
windowrule = move 50% 0, match:class ^(todo-app)$
windowrule = animation slide top, match:class ^(todo-app)$
windowrule = opacity 0.80, match:class ^(todo-app)$

windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
 
windowrule = no_blur on, match:tag multimedia_video*
windowrule = opacity 1.0, match:tag multimedia_video*

windowrule = opacity 0.95, match:class ^(kitty)$
windowrule = opacity 0.1, match:class ^(wofi)$
windowrule = opacity 0.85, match:class ^(waybar)$
windowrule = opacity 0.95, match:class ^(com.github.th_ch.youtube_music)$
windowrule = opacity 0.95, match:class ^(vesktop)$
windowrule = opacity 0.95, match:class ^(firefox)$
windowrule = opacity 0.95 0.95, match:class ^(org.qutebrowser.qutebrowser)$

layerrule = blur on, match:namespace wofi
layerrule = blur on, match:namespace logout_dialog
layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace quickshell
layerrule = ignore_alpha 0.0, match:namespace quickshell
# layerrule = blur_popups on, match:namespace quickshell
# layerrule = blur on, match:namespace quickshell
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.2, match:namespace swaync-control-center
layerrule = ignore_alpha 0.2, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace waybar
layerrule = blur off, match:namespace selection
layerrule = blur on, match:namespace discord
# layerrule = blur on, match:class ^(org.qutebrowser.qutebrowser)$
