# Core Colors
background            = {{ colors.surface.default.hex }}
foreground            = {{ colors.on_surface.default.hex }}
selection-foreground  = {{ colors.on_secondary.default.hex }}
selection-background  = {{ colors.primary.default.hex }}
cursor-color          = {{ colors.primary.default.hex }}
cursor-text           = {{ colors.on_secondary.default.hex }}

# Search Colors
search-foreground          = cell-background
search-background          = cell-foreground
search-selected-foreground = {{ colors.on_secondary.default.hex }}
search-selected-background = {{ colors.tertiary.default.hex }}

# Regular Colors
palette               = 0=#1e222a
palette               = 1=#e05f65
palette               = 2=#78dba9
palette               = 3=#f1cf8a
palette               = 4=#a8c8ff
palette               = 5=#dbbce1
palette               = 6=#74bee9
palette               = 7=#c5c6cc

# Brighter Colors
palette               = 8=#43474e
palette               = 9=#fc7b81
palette               = 10=#94f7c5
palette               = 11=#ffeba6
palette               = 12=#d5e3ff
palette               = 13=#f8d8fe
palette               = 14=#90daff
palette               = 15=#e1e2e9
